// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	request "payment-service/internal/modules/payment/models/request"

	response "payment-service/internal/modules/payment/models/response"
)

// MidtransRepositoryCommand is an autogenerated mock type for the MidtransRepositoryCommand type
type MidtransRepositoryCommand struct {
	mock.Mock
}

// TransferBank provides a mock function with given fields: ctx, payload
func (_m *MidtransRepositoryCommand) TransferBank(ctx context.Context, payload request.BankTransferRequest) (*response.BankTransferResponse, error) {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for TransferBank")
	}

	var r0 *response.BankTransferResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, request.BankTransferRequest) (*response.BankTransferResponse, error)); ok {
		return rf(ctx, payload)
	}
	if rf, ok := ret.Get(0).(func(context.Context, request.BankTransferRequest) *response.BankTransferResponse); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.BankTransferResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, request.BankTransferRequest) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMidtransRepositoryCommand creates a new instance of MidtransRepositoryCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMidtransRepositoryCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *MidtransRepositoryCommand {
	mock := &MidtransRepositoryCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
