// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"
	helpers "payment-service/internal/pkg/helpers"

	mock "github.com/stretchr/testify/mock"

	request "payment-service/internal/modules/payment/models/request"
)

// MongodbRepositoryQuery is an autogenerated mock type for the MongodbRepositoryQuery type
type MongodbRepositoryQuery struct {
	mock.Mock
}

// FindOrderByTicket provides a mock function with given fields: ctx, ticketNumber
func (_m *MongodbRepositoryQuery) FindOrderByTicket(ctx context.Context, ticketNumber string) <-chan helpers.Result {
	ret := _m.Called(ctx, ticketNumber)

	if len(ret) == 0 {
		panic("no return value specified for FindOrderByTicket")
	}

	var r0 <-chan helpers.Result
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan helpers.Result); ok {
		r0 = rf(ctx, ticketNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan helpers.Result)
		}
	}

	return r0
}

// FindPaymentById provides a mock function with given fields: ctx, id
func (_m *MongodbRepositoryQuery) FindPaymentById(ctx context.Context, id string) <-chan helpers.Result {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindPaymentById")
	}

	var r0 <-chan helpers.Result
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan helpers.Result); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan helpers.Result)
		}
	}

	return r0
}

// FindPaymentByTicketNumber provides a mock function with given fields: ctx, ticketNumber
func (_m *MongodbRepositoryQuery) FindPaymentByTicketNumber(ctx context.Context, ticketNumber string) <-chan helpers.Result {
	ret := _m.Called(ctx, ticketNumber)

	if len(ret) == 0 {
		panic("no return value specified for FindPaymentByTicketNumber")
	}

	var r0 <-chan helpers.Result
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan helpers.Result); ok {
		r0 = rf(ctx, ticketNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan helpers.Result)
		}
	}

	return r0
}

// FindPaymentByUser provides a mock function with given fields: ctx, payload
func (_m *MongodbRepositoryQuery) FindPaymentByUser(ctx context.Context, payload request.PaymentList) <-chan helpers.Result {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for FindPaymentByUser")
	}

	var r0 <-chan helpers.Result
	if rf, ok := ret.Get(0).(func(context.Context, request.PaymentList) <-chan helpers.Result); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan helpers.Result)
		}
	}

	return r0
}

// FindPaymentStatusById provides a mock function with given fields: ctx, id
func (_m *MongodbRepositoryQuery) FindPaymentStatusById(ctx context.Context, id string) <-chan helpers.Result {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindPaymentStatusById")
	}

	var r0 <-chan helpers.Result
	if rf, ok := ret.Get(0).(func(context.Context, string) <-chan helpers.Result); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan helpers.Result)
		}
	}

	return r0
}

// NewMongodbRepositoryQuery creates a new instance of MongodbRepositoryQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMongodbRepositoryQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *MongodbRepositoryQuery {
	mock := &MongodbRepositoryQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
